
/*
 * Copyright (C) 2006 by Digi International.
 * All rights reserved.
 *
 * U-Boot user configuration settings for the CC9C Embedded Module
 *
 * See file CREDITS for list of people who contributed to this
 * project.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 */

#ifndef __USER_SETTINGS_H_
#define __USER_SETTINGS_H_

/*
 * Here comes the specific user settings
 * Do not edit. This file is automatically generated by the LxNETES
 * build environment.
 */

#endif /* __USER_SETTINGS_H_ */

